export const assets = {
  video: "/assets/video.png",
  ipsy: "/assets/ipsy.png",
  productThumb: "/assets/product-thumb.png",
  neutral: "/assets/neutral.png",
  commentImage: "/assets/comment-image.png",
  play: "/assets/icon-play.svg",
  back: "/assets/icon-back.svg",
  fwd: "/assets/icon-fwd.svg",
  volume: "/assets/icon-volume.svg",
  caret: "/assets/icon-caret.svg",
  fullscreen: "/assets/icon-fullscreen.svg",
  tiktok: "/assets/icon-tiktok.svg",
  link: "/assets/icon-link.svg",
  expand: "/assets/icon-expand.svg",
  followers: "/assets/icon-followers.svg",
  brand: "/assets/icon-brand.svg",
  verified: "/assets/icon-verified.svg",
  views: "/assets/icon-views.svg",
  likes: "/assets/icon-likes.svg",
  comments: "/assets/icon-comments.svg",
  saves: "/assets/icon-saves.svg",
  shares: "/assets/icon-shares.svg",
  reposts: "/assets/icon-reposts.svg",
  er: "/assets/icon-er.svg",
  ctr: "/assets/icon-ctr.svg",
  chevron: "/assets/icon-chevron.svg",
  dropdown: "/assets/icon-dropdown.svg",
  report: "/assets/icon-report.svg",
  sentiment: "/assets/icon-sentiment.svg",
  sentimentSmile: "/assets/icon-sentiment-smile.svg",
  sentimentNegative: "/assets/sentiment-negative.svg",
  sentimentNeutral: "/assets/sentiment-neutral.svg",
  sentimentPositive: "/assets/sentiment-positive.svg",
  arrowLeft: "/assets/icon-arrow-left.svg",
  arrowRight: "/assets/icon-arrow-right.svg",
  shakira: "/assets/avatar-shakira.png",
  themeDot1: "/assets/theme-dot-1.svg",
  themeDot2: "/assets/theme-dot-2.svg",
  themeDot3: "/assets/theme-dot-3.svg",
  themeDotGreen: "/assets/theme-dot-green.svg",
  carouselNext: "/assets/post2/carousel-next.svg",
  post2: {
    slides: [
      "/assets/post2/slide-1.png",
      "/assets/post2/slide-2.png",
      "/assets/post2/slide-3.png",
      "/assets/post2/slide-4.png",
      "/assets/post2/slide-5.png",
      "/assets/post2/slide-6.png",
      "/assets/post2/slide-7.png",
      "/assets/post2/slide-8.png",
    ],
    thumb: "/assets/post2/thumb.png",
    lisbeth: "/assets/post2/avatar-lisbeth.png",
    lindsey: "/assets/post2/avatar-lindsey.png",
    huda: "/assets/post2/avatar-huda.png",
    chands: "/assets/post2/avatar-chands.png",
    madison: "/assets/post2/avatar-madison.png",
    chloe: "/assets/post2/avatar-chloe.png",
  },
  post3: {
    image: "/assets/post3/image.png",
    elf: "/assets/post3/avatar-elf.png",
    ashley: "/assets/post3/avatar-ashley.png",
    dandan: "/assets/post3/avatar-dandan.png",
    dani: "/assets/post3/avatar-dani.png",
    holly: "/assets/post3/avatar-holly.png",
  },
  avatars: [
    "/assets/avatar-1.png",
    "/assets/avatar-2.png",
    "/assets/avatar-3.png",
    "/assets/avatar-4.png",
    "/assets/avatar-5.png",
    "/assets/avatar-6.png",
    "/assets/avatar-7.png",
    "/assets/avatar-8.png",
    "/assets/avatar-9.png",
    "/assets/avatar-10.png",
    "/assets/avatar-11.png",
    "/assets/avatar-12.png",
    "/assets/avatar-13.png",
    "/assets/avatar-14.png",
  ],
} as const;
