const file = (path: string) => `${import.meta.env.BASE_URL}${path.replace(/^\//, "")}`;

export const assets = {
  video: file("/assets/video.png"),
  ipsy: file("/assets/ipsy.png"),
  productThumb: file("/assets/product-thumb.png"),
  neutral: file("/assets/neutral.png"),
  commentImage: file("/assets/comment-image.png"),
  play: file("/assets/icon-play.svg"),
  back: file("/assets/icon-back.svg"),
  fwd: file("/assets/icon-fwd.svg"),
  volume: file("/assets/icon-volume.svg"),
  caret: file("/assets/icon-caret.svg"),
  fullscreen: file("/assets/icon-fullscreen.svg"),
  tiktok: file("/assets/icon-tiktok.svg"),
  link: file("/assets/icon-link.svg"),
  expand: file("/assets/icon-expand.svg"),
  followers: file("/assets/icon-followers.svg"),
  brand: file("/assets/icon-brand.svg"),
  verified: file("/assets/icon-verified.svg"),
  views: file("/assets/icon-views.svg"),
  likes: file("/assets/icon-likes.svg"),
  comments: file("/assets/icon-comments.svg"),
  saves: file("/assets/icon-saves.svg"),
  shares: file("/assets/icon-shares.svg"),
  reposts: file("/assets/icon-reposts.svg"),
  er: file("/assets/icon-er.svg"),
  ctr: file("/assets/icon-ctr.svg"),
  chevron: file("/assets/icon-chevron.svg"),
  dropdown: file("/assets/icon-dropdown.svg"),
  report: file("/assets/icon-report.svg"),
  sentiment: file("/assets/icon-sentiment.svg"),
  sentimentSmile: file("/assets/icon-sentiment-smile.svg"),
  sentimentNegative: file("/assets/sentiment-negative.svg"),
  sentimentNeutral: file("/assets/sentiment-neutral.svg"),
  sentimentPositive: file("/assets/sentiment-positive.svg"),
  arrowLeft: file("/assets/icon-arrow-left.svg"),
  arrowRight: file("/assets/icon-arrow-right.svg"),
  shakira: file("/assets/avatar-shakira.png"),
  themeDot1: file("/assets/theme-dot-1.svg"),
  themeDot2: file("/assets/theme-dot-2.svg"),
  themeDot3: file("/assets/theme-dot-3.svg"),
  themeDotGreen: file("/assets/theme-dot-green.svg"),
  carouselNext: file("/assets/post2/carousel-next.svg"),
  post2: {
    slides: [
      file("/assets/post2/slide-1.png"),
      file("/assets/post2/slide-2.png"),
      file("/assets/post2/slide-3.png"),
      file("/assets/post2/slide-4.png"),
      file("/assets/post2/slide-5.png"),
      file("/assets/post2/slide-6.png"),
      file("/assets/post2/slide-7.png"),
      file("/assets/post2/slide-8.png"),
    ],
    thumb: file("/assets/post2/thumb.png"),
    lisbeth: file("/assets/post2/avatar-lisbeth.png"),
    lindsey: file("/assets/post2/avatar-lindsey.png"),
    huda: file("/assets/post2/avatar-huda.png"),
    chands: file("/assets/post2/avatar-chands.png"),
    madison: file("/assets/post2/avatar-madison.png"),
    chloe: file("/assets/post2/avatar-chloe.png"),
  },
  post3: {
    image: file("/assets/post3/image.png"),
    elf: file("/assets/post3/avatar-elf.png"),
    ashley: file("/assets/post3/avatar-ashley.png"),
    dandan: file("/assets/post3/avatar-dandan.png"),
    dani: file("/assets/post3/avatar-dani.png"),
    holly: file("/assets/post3/avatar-holly.png"),
  },
  avatars: [
    file("/assets/avatar-1.png"),
    file("/assets/avatar-2.png"),
    file("/assets/avatar-3.png"),
    file("/assets/avatar-4.png"),
    file("/assets/avatar-5.png"),
    file("/assets/avatar-6.png"),
    file("/assets/avatar-7.png"),
    file("/assets/avatar-8.png"),
    file("/assets/avatar-9.png"),
    file("/assets/avatar-10.png"),
    file("/assets/avatar-11.png"),
    file("/assets/avatar-12.png"),
    file("/assets/avatar-13.png"),
    file("/assets/avatar-14.png"),
  ],
};
