const file = (path: string) => `${import.meta.env.BASE_URL}${path.replace(/^\//, "")}`;

export const assets = {
  video: file("/assets/video.png"),
  fabletics: file("/assets/fabletics.jpg"),
  productThumb: file("/assets/product-thumb.png"),
  neutral: file("/assets/neutral.png"),
  commentImage: file("/assets/comment-image.png"),
  play: file("/assets/icon-play.svg"),
  back: file("/assets/icon-back.svg"),
  fwd: file("/assets/icon-fwd.svg"),
  volume: file("/assets/icon-volume.svg"),
  caret: file("/assets/icon-caret.svg"),
  fullscreen: file("/assets/icon-fullscreen.svg"),
  tiktok: file("/assets/icon-tiktok.svg"),
  link: file("/assets/icon-link.svg"),
  expand: file("/assets/icon-expand.svg"),
  followers: file("/assets/icon-followers.svg"),
  brand: file("/assets/icon-brand.svg"),
  verified: file("/assets/icon-verified.svg"),
  views: file("/assets/icon-views.svg"),
  likes: file("/assets/icon-likes.svg"),
  comments: file("/assets/icon-comments.svg"),
  saves: file("/assets/icon-saves.svg"),
  shares: file("/assets/icon-shares.svg"),
  reposts: file("/assets/icon-reposts.svg"),
  er: file("/assets/icon-er.svg"),
  ctr: file("/assets/icon-ctr.svg"),
  chevron: file("/assets/icon-chevron.svg"),
  dropdown: file("/assets/icon-dropdown.svg"),
  report: file("/assets/icon-report.svg"),
  sentiment: file("/assets/icon-sentiment.svg"),
  sentimentSmile: file("/assets/icon-sentiment-smile.svg"),
  sentimentNegative: file("/assets/sentiment-negative.svg"),
  sentimentNeutral: file("/assets/sentiment-neutral.svg"),
  sentimentPositive: file("/assets/sentiment-positive.svg"),
  arrowLeft: file("/assets/icon-arrow-left.svg"),
  arrowRight: file("/assets/icon-arrow-right.svg"),
  shakira: file("/assets/avatar-shakira.png"),
  themeDot1: file("/assets/theme-dot-1.svg"),
  themeDot2: file("/assets/theme-dot-2.svg"),
  themeDot3: file("/assets/theme-dot-3.svg"),
  themeDotGreen: file("/assets/theme-dot-green.svg"),
  carouselNext: file("/assets/post2/carousel-next.svg"),
  post1: {
    slides: [
      file("/assets/post1/slide-1.jpg"),
      file("/assets/post1/slide-2.jpg"),
      file("/assets/post1/slide-3.jpg"),
    ],
    thumb: file("/assets/post1/thumb.jpg"),
    katrina: file("/assets/post1/avatar-katrina.jpg"),
    michelle: file("/assets/post1/avatar-michelle.jpg"),
    lettie: file("/assets/post1/avatar-lettie.jpg"),
    remy: file("/assets/post1/avatar-remy.jpg"),
    pierre: file("/assets/post1/avatar-pierre.jpg"),
    carlah: file("/assets/post1/avatar-carlah.jpg"),
    sophia: file("/assets/post1/avatar-sophia.jpg"),
  },
  post2: {
    slides: [
      file("/assets/post2/slide-1.jpg"),
      file("/assets/post2/slide-2.jpg"),
      file("/assets/post2/slide-3.jpg"),
      file("/assets/post2/slide-4.jpg"),
    ],
    thumb: file("/assets/post2/thumb.jpg"),
    rathana: file("/assets/post2/avatar-rathana.jpg"),
    daria: file("/assets/post2/avatar-daria.jpg"),
    maurissa: file("/assets/post2/avatar-maurissa.jpg"),
    lettie: file("/assets/post2/avatar-lettie.jpg"),
  },
  post3: {
    slides: [
      file("/assets/post3/slide-1.jpg"),
      file("/assets/post3/slide-2.jpg"),
      file("/assets/post3/slide-3.jpg"),
      file("/assets/post3/slide-4.jpg"),
    ],
    thumb: file("/assets/post3/thumb.jpg"),
    jessRose: file("/assets/post3/avatar-jess-rose.jpg"),
    katrina: file("/assets/post3/avatar-katrina.jpg"),
    jessA: file("/assets/post3/avatar-jess-a.jpg"),
    taryn: file("/assets/post3/avatar-taryn.jpg"),
    nia: file("/assets/post3/avatar-nia.jpg"),
    sarah: file("/assets/post3/avatar-sarah.jpg"),
    kim: file("/assets/post3/avatar-kim.jpg"),
  },
  avatars: [
    file("/assets/avatar-1.png"),
    file("/assets/avatar-2.png"),
    file("/assets/avatar-3.png"),
    file("/assets/avatar-4.png"),
    file("/assets/avatar-5.png"),
    file("/assets/avatar-6.png"),
    file("/assets/avatar-7.png"),
    file("/assets/avatar-8.png"),
    file("/assets/avatar-9.png"),
    file("/assets/avatar-10.png"),
    file("/assets/avatar-11.png"),
    file("/assets/avatar-12.png"),
    file("/assets/avatar-13.png"),
    file("/assets/avatar-14.png"),
  ],
};
