const file = (path: string) => `${import.meta.env.BASE_URL}${path.replace(/^\//, "")}`;

export const chatAssets = {
  back: file("/assets/chat/icon-back.svg"),
  close: file("/assets/chat/icon-close.svg"),
  send: file("/assets/chat/icon-send.svg"),
  sendDisabled: file("/assets/chat/icon-send-disabled.svg"),
  intercom: file("/assets/chat/icon-intercom.svg"),
  statusSpin: file("/assets/chat/icon-status-spin.svg"),
  edit: file("/assets/chat/icon-edit.svg"),
  check: file("/assets/chat/icon-check.svg"),
  chevronLeft: file("/assets/chat/icon-chevron-left.svg"),
  chevronRight: file("/assets/chat/icon-chevron-right.svg"),
  checkBox: file("/assets/chat/icon-check-box.svg"),
  checkBoxEmpty: file("/assets/chat/icon-check-box-empty.svg"),
  brand: file("/assets/chat/brand-anthropologie.png"),
  avatarRhea: file("/assets/chat/avatar-rhea.png"),
  caretDown: file("/assets/chat/icon-caret-down.svg"),
  caretDown16: file("/assets/chat/icon-caret-down-16.svg"),
  caretUp: file("/assets/chat/icon-caret-up.svg"),
  sidebar: file("/assets/chat/icon-sidebar.svg"),
  notification: file("/assets/chat/icon-notification.svg"),
  messages: file("/assets/chat/icon-messages.svg"),
  navRule: file("/assets/chat/icon-nav-rule.svg"),
  home: file("/assets/chat/icon-home.svg"),
  engagement: file("/assets/chat/icon-engagement.svg"),
  topics: file("/assets/chat/icon-topics.svg"),
  brandAnalytics: file("/assets/chat/icon-brand-analytics.svg"),
  competitor: file("/assets/chat/icon-competitor.svg"),
  outbound: file("/assets/chat/icon-outbound.svg"),
  community: file("/assets/chat/icon-community.svg"),
  sourcing: file("/assets/chat/icon-sourcing.svg"),
  trends: file("/assets/chat/icon-trends.svg"),
  juicebox: file("/assets/chat/icon-juicebox.svg"),
  juiceboxMark: file("/assets/chat/icon-juicebox-mark.svg"),
  bookmarks: file("/assets/chat/icon-bookmarks.svg"),
  profileRule: file("/assets/chat/icon-profile-rule.svg"),
  settings: file("/assets/chat/icon-settings.svg"),
  more: file("/assets/chat/icon-more.svg"),
  topic: file("/assets/chat/icon-topic.svg"),
  report: file("/assets/chat/icon-report.svg"),
  editSm: file("/assets/chat/icon-edit-sm.svg"),
};
